# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'testdispatch-ipxoa-uv'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080 # L'application écoute sur le port 8080 à l'intérieur du conteneur.
  force_https = true # Forcer l'utilisation de HTTPS (redirige automatiquement HTTP vers HTTPS).
  auto_stop_machines = true # Active l'arrêt automatique. Arrête automatiquement les machines inactives pour économiser des ressources.
  stop_timeout = '10m'  # Temps avant l'arrêt : 10 minutes
  auto_start_machines = true # Redémarre automatiquement les machines lorsqu'une requête arrive.
  min_machines_running = 0 # Autorise l'arrêt total des machines lorsqu'elles ne sont pas utilisées.
  processes = ['app'] # Définit les processus exécutés par l'application.

[[vm]]
  memory = '8gb' # 8 Go de RAM
  cpu_kind = 'shared' # 'shared' : Utilisation de CPU partagé (moins cher, mais partagé avec d'autres)
  cpus = 4 # La machine a 4 CPU
  memory_mb = 8192  # memoire en mb
